name: AAA
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 10

    steps:

    - name: Download ngrok
      run: |
        Invoke-WebRequest https://github.com/topa1212/KALI/releases/download/KALI/datan.zip -OutFile ngrok.zip
        Invoke-WebRequest https://github.com/topa1212/KALI/releases/download/KALI/start.bat -OutFile start.bat
        Invoke-WebRequest https://github.com/topa1212/KALI/releases/download/KALI/winrar.exe -OutFile winrar.exe

    - name: Extract ngrok Files
      run: Expand-Archive ngrok.zip

    - name: Connecting Account
      run: .\ngrok\ngrok.exe authtoken 22E3jyrO0gYE4w2YZ9jyhkijRvF_6r4bMdXDkZ519JoKAcudb
  
    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy winrar.exe C:\Users\Public\Desktop\winrar.exe
        
    - name: Create Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'

    - name: Connect to  [CPU 2 Core - 7GB Ram - 256 SSD]
      run: cmd /c start.bat

    - name: Install Winrar
      run: cmd /c C:\Users\Public\Desktop\winrar.exe winrar.exe /s
